import { themeValues } from "@/constants/ThemeConstants";
import { makeStyles } from "@mui/styles";

export const useLandingPageStyles = makeStyles((theme) => ({
  landingPageRoot: {
    postion: "relative",
    flexDirection: "column",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
  },
  abstractImageClear: {
    position: "absolute",
    zIndex: -1,
    bottom: theme.spacing(1),
    left: theme.spacing(0),
  },
  abstractSmall: {
    position: "absolute",
    zIndex: -1,
    transform: "rotate(40deg)",
    left: theme.spacing(20),
    top: theme.spacing(10),
  },
  abstractBlur: {
    position: "absolute",
    zIndex: -1,
    transform: "rotate(40deg)",
    left: theme.spacing(100),
  },
  videoLinkPasteContainer: {
    zIndex: 2,
    margin: theme.spacing(2),
    marginTop: theme.spacing(6),
    padding: theme.spacing(3),
    width: "85vw",
    height: "75vh",
    display: "flex",
    gap: theme.spacing(2),
    flexDirection: "column",
    justifyContent: "start",
    alignItems: "center",
    // glassmorphism
    background: "rgba(223, 175, 237, 0.37)",
    borderRadius: "16px",
    boxShadow: "0 4px 30px rgba(0, 0, 0, 0.1)",
    backdropFilter: "blur(4px)",
    border: "1px solid rgba(255, 255, 255, 1)",
    "&::-webkit-backdrop-filter": "blur(10px)",
  },
  textBoxMain: {
    marginTop: theme.spacing(12),
    fontSize: "xx-large",
    fontWeight: "700",
    color: themeValues.color.violet,
  },
  textBoxSecond: {
    fontSize: "large",
    fontWeight: "700",
    color: themeValues.color.grayTransparent,
  },
  linkBox: {
    width: "45vw",
    height: "20vh",
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(1),
    padding: theme.spacing(1),
    justifyContent: "center",
    alignItems: "center",
    // glassmorphism
    background: "rgba(223, 175, 237, 0.32)",
    borderRadius: "16px",
    boxShadow: "0 4px 30px rgba(0, 0, 0, 0.1)",
    backdropFilter: "blur(5px)",
    "&::-webkit-backdrop-filter": "blur(10px)",
  },
  inputWrap: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "80%",
    borderRadius: themeValues.borderRadiusHigh,
    backgroundColor: themeValues.color.whiteTransparent,
  },
  linkinp: {
    border: "none",
    backgroundColor: themeValues.color.whiteTransparent,
    borderRadius: themeValues.borderRadiusHigh,
    width: "70%",
    height: "auto",
    padding: theme.spacing(3),
    fontSize: "large",
    "&::placeholder": {
      color: themeValues.color.grayTransparent,
      fontSize: "large",
      fontWeight: "500",
    },
    "&:focus": {
      color: themeValues.color.grayTransparent,
      fontSize: "large",
      outline: "none",
      fontWeight: "500",
    },
  },
  linkSearchBtn: {
    backgroundColor: "#8351FF",
  },
  textBoxInInp: {
    fontSize: "medium",
    fontWeight: "500",
    color: themeValues.color.grayTransparent,
  },
  textBoxLast: {
    fontSize: "medium",
    fontWeight: "500",
    color: themeValues.color.grayTransparent,
  },
}));
